resolver: lts-8.2
packages:
  - ./persistent
  - ./persistent-template
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-mysql-haskell
  - ./persistent-postgresql
  - ./persistent-redis

extra-deps:
  - tcp-streams-0.6.0.0
  - wire-streams-0.1.1.0
  - binary-0.8.3.0
  - binary-ieee754-0.1.0.0
  - word24-2.0.1